# Our PostgreSQL service:
postgres:
  image: postgres:9.4.5
  ports:
    - "5432:5432" 
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: neveralone

neo4j:
  image: neo4j/neo4j:latest
  ports:
    - "7474:7474"
  environment:
    NEO4J_AUTH: neo4j/NeverAlone

web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/django
  ports:
    - "8000:8000"
  links:
    - postgres
    - neo4j